const skills = [
    "react.svg",
    "Logo_C_sharp.svg",
    // "nextjs.svg",
    "js.svg",
    "Typescript_logo_2020.svg",
    "html.svg",
    "css.svg",
    // "framer-motion.svg",
    // "nodejs.svg",
    // "express.svg",
    // "python.svg",
    "bootstrap.svg",
    "NET_Core_Logo.svg",
    "Microsoft_.NET_logo.svg",
    "sql.svg",
    "sql-server-logo-white.png",
    "git.svg",
    "github.svg",
    "jira-1.svg",
    // "mongodb.svg",
    // "tailwind.svg",
  ];
  
  export default skills;