const skills = [
  "react.svg",
  // "nextjs-icon-svgrepo-com.svg",
  "Logo_C_sharp.svg",
  "nextjs.svg",
  "js.svg",
  "Typescript_logo_2020.svg",
  // "html.svg",
  // "css.svg",
  // "framer-motion.svg",
  "nodejs.svg",
  "postgresql-vertical.svg",
  // "express.svg",
  "python.svg",
  "FastAPI.svg",
  // "bootstrap.svg",
  "NET_Core_Logo.svg",
  "Microsoft_.NET_logo.svg",
  // "sql.svg",
  "git.svg",
  "mongodb-svgrepo-com.svg",
  "github.svg",
  // "jira-1.svg",
  "prisma-3.svg",
  // "mongodb.svg",
  // "tailwind.svg",
];

export default skills;
